name: Daily French Email

on:
  schedule:
    - cron: '0 9 * * *'  # This will trigger the action every day at 9:00 AM UTC.
  workflow_dispatch:  # Allows manual triggering if needed.

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the appropriate Python version

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script
      - name: Run daily email script
        run: |
          python main.py
